name: Manual Build and Package Release

on:
  workflow_dispatch:

jobs:
  build_and_package:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            release_suffix: linux-x64
          - os: macos-13
            release_suffix: macos-x64
          - os: macos-latest
            release_suffix: macos-arm64
          - os: windows-latest
            release_suffix: windows-x64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 17 (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build
        run: ./gradlew build

      - name: Package Release
        run: ./gradlew packageReleaseDistributionForCurrentOS

      - name: Upload Release Binaries
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.release_suffix }}
          path: build/compose/binaries/main-release
