name: Manual Build and Package App

on:
  workflow_dispatch:

jobs:
  build_and_package:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            release_suffix: linux
          - os: macos-latest
            release_suffix: mac
          - os: windows-latest
            release_suffix: windows
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 17 (Corretto)
        uses: actions/setup-java@v2
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build
        run: ./gradlew build

      - name: Package Release
        run: ./gradlew packageReleaseDistributionForCurrentOS

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.release_suffix }}
          path: build/libs/
