name: Manual Package Release

on:
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/check.yml

  package:
    needs: check

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platformName: "Linux"
            architectureId: "x64"
          - os: macos-13
            platformName: "Apple"
            architectureId: "x64"
          - os: macos-latest
            platformName: "Apple"
            architectureId: "arm64"
          - os: windows-latest
            platformName: "Windows"
            architectureId: "x64"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          distribution: "jetbrains"
          java-version: "17"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Release
        run: ./gradlew packageReleaseDistributionForCurrentOS

      - name: Move Artifacts to Common Directory
        run: ./gradlew moveReleaseBinaryFor${{ matrix.platformName }} -Parch=${{ matrix.architectureId }}

      - name: Upload Release Binaries
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.platformName }}-${{ matrix.architectureId }}
          path: build/compose/binaries/repository

  merge-artifacts:
    needs: package
    runs-on: ubuntu-latest

    steps:
      - name: Merge Binaries
        uses: actions/upload-artifact/merge@v4
        with:
          name: all-releases
          pattern: release-*
