name: Manual Package Release

on:
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/check.yml

  package:
    needs: check

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            release_suffix: linux-x64
          - os: macos-13
            release_suffix: macos-x64
          - os: macos-latest
            release_suffix: macos-arm64
          - os: windows-latest
            release_suffix: windows-x64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          distribution: "jetbrains"
          java-version: "17"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Release
        run: ./gradlew packageDistributionForCurrentOS

      - name: Upload Release Binaries
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.release_suffix }}
          path: build/compose/binaries/main-release
